name: Build C Program 2

on: [push]

jobs:
  build:
    name: Build Hello World
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Compile C program
      run: |
        gcc hello.c -o hello.exe
        dir  # Print directory contents for debugging
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hello.exe
        git commit -m "Add compiled executable"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
